### ISSUE TITLE
Don,t appears chart in react-router project

### ISSUE THREAD

**Issue by jinqifeng** [revolunet/react-analytics-widget#1]
thank you for your work. 
I am working with it on react-router application.
But don,t show chart.
login is succesed, But GooleDatachart does not show data in chart.
there is only blank chart boder.
I think data don't translate to Googledatachart.

I give you regard again for your wonderful work

**Comment by revolunet** [comment]
and what does the console/network says ?

**Comment by revolunet** [comment]
you an try with latest 1.0.3, fixes some unmount/remount issues
