### ISSUE TITLE
GoogleDataChart component does not mount again

### ISSUE THREAD

**Issue by npatrick** [revolunet/react-analytics-widget#2]
Hi revolunet!

I came across with a bug while trying to integrate your widget on my app. As mentioned on the title, when navigating to my other components and navigating back to the page where the widget is, GoogleDataChart component does not seem to be mounted again.

Here's a quick preview:
![new-tab](https://user-images.githubusercontent.com/17955215/36712915-f7114f18-1b3f-11e8-92e2-8d3b8985684c.gif)

I added logs on your widget (for both componentDidMount on GoogleProvider and GoogleDataChart components) to see if they really get called or not.
On the first visit these are what gets called:
![chrome-logs](https://user-images.githubusercontent.com/17955215/36713164-0f2c1096-1b41-11e8-8e65-cac9ca4d6e28.png)

Then, revisiting /reports... only GoogleProvider gets mounted
![chrome-logs-2](https://user-images.githubusercontent.com/17955215/36713181-252883ca-1b41-11e8-9abf-ca563b6e5b43.png)

I would greatly appreciate your input on this. Thanks!

**Comment by revolunet** [comment]
Hi, should be fixed in `v1.0.3`, can you confirm ?

**Comment by npatrick** [comment]
Yes, that did it! Thank you for the quick response.
