### ISSUE TITLE
All Google chart types are not working with the module.

### ISSUE THREAD

**Issue by hamidraza5** [revolunet/react-analytics-widget#6]

**Comment by revolunet** [comment]
what do you mean by "All Google chart types are not working with the module" ?

The demo looks ok : https://revolunet.github.io/react-analytics-widget/

**Comment by hamidraza5** [comment]
Thanks for getting back revolunt !
 In chart type only LINE, BAR and CLUMN are working. I'm unsuccessful in getting Geo, Scatter and other charts offered by Google Charts through this module.

**Comment by winniethefoo** [comment]
> Thanks for getting back revolunt !
> In chart type only LINE, BAR and CLUMN are working. I'm unsuccessful in getting Geo, Scatter and other charts offered by Google Charts through this module.

Double check your metrics and dimensions are valid in data studio
